// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include <fstream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1 3x3() ", "[example]")
{
	int numbers[MAX] = {0, 1, 2, 3, 4, 5, 6, 7, 8};
	/*****************************************
	 * 0 	1 	2
	 * 3	4	5
	 * 6	7	8
	 *****************************************/
	int result[MAX];
	int rows = 3;
	int cols = 3;
	int row = 2;
	int col = 1;

	getRow(numbers, rows, cols, row, result);
	REQUIRE(result[0] == 3);
	REQUIRE(result[1] == 4);
	REQUIRE(result[2] == 5);
	for (int i = 0; i < cols; i++)
		cout << result[i] << "\t";
	cout << " The result array " << endl;

	getCol(numbers, rows, cols, col, result);
	REQUIRE(result[0] == 0);
	REQUIRE(result[1] == 3);
	REQUIRE(result[2] == 6);
	for (int i = 0; i < rows; i++)
		cout << result[i] << "\t";
	cout << " The result array " << endl;
}
TEST_CASE("Ex2 5x4() ", "[example]")
{
	int numbers[MAX] = {6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 16, 17, 18, 19, 20, 11, 12, 13, 14, 15};
	/*****************************************
	6	7	8	9	10
	1	2	3 	4	5
	16	17 	18	19	20
	11	12 	13	14	15
	*****************************************/
	int result[MAX];
	int rows = 4;
	int cols = 5;
	int row = 4;
	int col = 4;

	getRow(numbers, rows, cols, row, result);
	for (int i = 0; i < cols; i++)
		cout << result[i] << "\t";
	cout << " The result array " << endl;
	REQUIRE(result[0] == 11);
	REQUIRE(result[1] == 12);
	REQUIRE(result[2] == 13);
	REQUIRE(result[3] == 14);
	REQUIRE(result[4] == 15);

	getCol(numbers, rows, cols, col, result);
	for (int i = 0; i < rows; i++)
		cout << result[i] << "\t";
	cout << " The result array " << endl;
	REQUIRE(result[0] == 9);
	REQUIRE(result[1] == 4);
	REQUIRE(result[2] == 19);
	REQUIRE(result[3] == 14);
}